### PR TITLE
Add retry(_:condition:) method.

### PR DESCRIPTION
**Pull request by r-plus**
Hi, I want conditional retryable feature.
In my use case, I want retry failed task with date time predication like this.

```
task.retry(5) { () -> Bool in
  let now = NSDate()
  return now.compare(expireDate) == .OrderedAscending
}.success { (value) -> Void in
 ...
```

What do you think about this?

### CODE REVIEW

**Comment by inamiy** [comment]
@r-plus 
Hi, thank you for pull request! ✨ 
I like this idea, and I think `retry`'s `condition` type can be improved as `Error -> Bool` so that it is stoppable from received error.

**Comment by r-plus** [comment]
hi @inamiy, it is good idea.
Changed to pass `ErrorInfo` to condition argument.

And also fixed condition evaluation on first try. I think it is not retry.

**Comment by inamiy** [comment]
Thanks for fix!
There was a bit of difficulty dealing with `ErrorInfo` instead of `Error`, so I made another fix in 
https://github.com/ReactKit/SwiftTask/commit/26b127892675cdd61e321a42d08c061002817f5b .
Please take a look.

Hopefully, this will answer to your needs (including test code fix).
If you are OK, please cherry-pick it and I will merge this PR!

**Comment by r-plus** [comment]
Wow, cleanly and easy readable implementation!
No objection. 👍 
I appreciate to your help. 🌟

**Comment by inamiy** [comment]
@r-plus Thanks for your contribution! Merged.

**Pull request merged**
