### PR TITLE
update MACOSX_DEPLOYMENT_TARGET to 10.10

### PR DESCRIPTION
**Pull request by DanielAsher**
I believe updating macosx deployment target to 10.10 is required to get SwiftTask to work in xc_8.3 playgrounds.

### CODE REVIEW

**Comment by inamiy** [comment]
Can you provide a demo for this as well?
I tried https://github.com/ReactKit/SwiftTask/pull/28#issuecomment-91499339 , and it just works fine without this fix.

**Comment by inamiy** [comment]
I just pushed https://github.com/ReactKit/SwiftTask/pull/30 for Playground demo.
Please take a try.

As demo is running properly, this fix doesn't seem necessary, so I will close this issue.

**Comment by inamiy** [comment]
Oh, by the way, https://github.com/duemunk/Async required OSX 10.10 and maybe you were using this library inside Playground as well.

**Comment by DanielAsher** [comment]
Hi - thanks for checking this. I do have other dependencies and should have verified with the sample I provided.

**Pull request closed without merging**
